name: Generate Snake

on:
  schedule: # Run at a scheduled time
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/github-snake.svg
